### ISSUE TITLE
コメント欄の表示を改善する

### ISSUE THREAD

**Issue by o-xian999** [kyutech-programming-club/lt-hub#102]
- 最新のコメントを一番下に持ってくる
- 入力フォームを下に移動させる

**Comment by o-xian999** [comment]
Vue.js　v-for　レンダリングの並び順を変える（昇順、降順）
https://qiita.com/Takmonkey/items/d06d2893ac4baf805ac1

**Comment by o-xian999** [comment]
- Scroll to bottom of div with Vue.js
https://stackoverflow.com/questions/40730116/scroll-to-bottom-of-div-with-vue-js
 
- nuxtで非同期で取得したデータに合わせてチャットを一番下までスクロールする
https://qiita.com/0ba/items/4c4e4d3f8253b1e3ddec

**Comment by syu-kwsk** [comment]
@o-xian999 

> Vue.js　v-for　レンダリングの並び順を変える（昇順、降順）
> https://qiita.com/Takmonkey/items/d06d2893ac4baf805ac1

vueのレンダリングで並び順を変えるんじゃなくてfirestoreからとってくるときの並びを変えた方が無駄な処理が少なそう 
該当箇所: https://github.com/kyutech-programming-club/lt-hub/blob/master/src/components/CommentBoard.vue#L71

**Comment by o-xian999** [comment]
それなら、firebaseをメインに１回実装してみましょうか

**Comment by syu-kwsk** [comment]
メインかどうかはわからないけど、firestoreから取ってくる並びを作成日の昇順にすれば新しいコメントは下に来ると思うよ  
スクロールは貼ってたやつも含めて考える必要があると思う

**Comment by syu-kwsk** [comment]
スクロールはできそうかも（コミットしてない）

https://user-images.githubusercontent.com/39556764/104952511-febcf780-5a07-11eb-9cd7-b3f8fed0eea8.mp4

動画載せるの使ったことなかったのでやってみた(´・ω・｀)

参考コード

```bottom.js
updated() {
  this.scrollToEnd()
},
methods: {
  scrollToEnd() {   
      this.$nextTick(() => {
      const chatLog = this.$refs.target
      if (!chatLog) return
      chatLog.$refs.link.scrollTop = chatLog.$refs.link.scrollHeight
      })
  },
},
```
