### ISSUE TITLE
参加しているイベントのカードの色を変えたい

### ISSUE THREAD

**Issue by o-xian999** [kyutech-programming-club/lt-hub#106]
- 今は参加しているLT会には「参加済み」のラベルが貼られる。
- これをなくして、参加しているLT会のカードの色を濃いものにしたい

**Comment by tetuomi** [comment]
https://github.com/kyutech-programming-club/lt-hub/blob/master/src/components/EventItem.vue

**Comment by o-xian999** [comment]
- 「Firebaseの認証情報を調べて、NullじゃなければVuetifyのカラー設定プロパティに違う値を入れる」みたいなことをすればいいと思う

**Comment by tetuomi** [comment]
これの```isparticipated```で色を分けてあげればいいと思う。
trueで参加済み
