### ISSUE TITLE
Vuexについて調査

### ISSUE THREAD

**Issue by syu-kwsk** [kyutech-programming-club/lt-hub#118]
# やりたいこと
- [ ] ログインユーザーの状態を各コンポーネントではなくて一箇所で管理したい
- [ ]  （イベントやトークなどのデータもvuexで管理したい）
- [ ]  （firestoreとの通信はすべてvuexを通して行い、各コンポーネントではvuexの状態を用いてレンダリングさせる）

# 調査したいこと
- [ ]  何ができるか
- [ ]  ファイル構成・それぞれの役割
- [ ]  実装方針

**Comment by syu-kwsk** [comment]
### Vuexについて
- 公式
[Vuexとは何か？](https://vuex.vuejs.org/ja/)
[Vuex入門](https://vuex.vuejs.org/ja/guide/)

### VuexとTypeScriptについて

- Qiitaの記事
https://qiita.com/yam0918/items/68d4d6c74b06d589a195

- その中で紹介されている英語の記事
https://codeburst.io/vuex-and-typescript-3427ba78cfa8

**Comment by yattinda** [comment]
https://qiita.com/kwashi/items/0bc56d79f7d198396a3f#%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E7%AE%A1%E7%90%86%E5%87%A6%E7%90%86%E3%81%AE%E5%AE%9F%E8%A3%85
実例

storeをよく理解死体

**Comment by yattinda** [comment]
https://qiita.com/kouki-iwahara/items/1a75daaa93657b0b56d7

storeの解説

**Comment by syu-kwsk** [comment]
[TypeScript Support](https://next.vuex.vuejs.org/guide/typescript-support.html)

**Comment by syu-kwsk** [comment]
Vuetifyがvue3に対応されたらそれに合わせてvue3, vuex4に上げればtypescriptのサポートがより良くなりそう
