### ISSUE TITLE
ログイン状態をvuexで管理する

### ISSUE THREAD

**Issue by syu-kwsk** [kyutech-programming-club/lt-hub#124]
- onAuthStateChangedをコンポーネント毎に呼ぶのを廃止
- ログイン中のUserの情報をvuexで管理する

**Comment by syu-kwsk** [comment]
やりたいことが似ている記事を発見した
https://qiita.com/kaz_goto/items/ef6d491c27babda2f936

これを参考に、vuex, firestoreの扱いを学ぼうと思います

**Comment by syu-kwsk** [comment]
firebaseのログインなどをpluginの中に書いてコンポーネントは関数呼び出しとかcommit呼ぶぐらいにします。

**Comment by syu-kwsk** [comment]
> firebaseのログインなどをpluginの中に書いてコンポーネントは関数呼び出しとかcommit呼ぶぐらいにします。


参考
- [Vue vuexでfirebaseのログイン保持
](https://qiita.com/ErgoFriend/items/bd1bb445e185bf45e272)
- [Firebase の Google 認証情報を Vuex で状態管理しよう
](https://qiita.com/kurararara/items/dac8d5cd51cd5f1ae632)

**Comment by yattinda** [comment]
https://volpe.hatenablog.com/entry/2019/04/01/094815

bindFirestoreRefがよくわからなかったのでメモ

**Comment by syu-kwsk** [comment]
issue: #125 #126 
request: #127 #128 
でvuexを使わないことを使わない方針で行くことになったので閉じ
