### ISSUE TITLE
参加意思表示のデータの保存の仕方

### ISSUE THREAD

**Issue by syu-kwsk** [kyutech-programming-club/lt-hub#14]
### やりたいこと
+ Event一覧でイベントごとに参加ボタンを表示
+ 参加してたら参加ボタンをなくす
+ Event詳細で参加者リストを表示

**_実現するにはコレクションとかドキュメントのデータとかどんなふうにする？_**

**Comment by syu-kwsk** [comment]
### Eventのサブコレクションをつくって参加者を入れていく
[https://firebase.google.com/docs/firestore/data-model?hl=ja#subcollections](https://firebase.google.com/docs/firestore/data-model?hl=ja#subcollections)

参加者を参照型で入れられたら、User名を変更しても反映できそう
[firestoreのデータ型](https://firebase.google.com/docs/firestore/manage-data/data-types?authuser=2)

**Comment by tanacchi** [comment]
そうだね，`Event` に `participants` か何かを
 `User` リファレンスの配列としてもたせるとかが正解だと思う．

多分だけど `Event` のサブコレクションに参加者を持たせるのもそうだし，
ユーザのページから参加しているイベントを参照するために
`User` のサブコレクションに `events` を持たせなきゃいけないと思う．
（議論の余地あり）

リレーショナル・データベースじゃないからその辺りよく知らないけど

**Comment by yattinda** [comment]
できたよ
