### ISSUE TITLE
ユーザー登録

### ISSUE THREAD

**Issue by rkdora** [kyutech-programming-club/lt-hub#2]
- ログイン
- ログアウト

**Comment by rkdora** [comment]
Github認証の難易度、実現可能性を調べる必要あり。

**Comment by rkdora** [comment]
参考文献

https://cr-vue.mio3io.com/tutorials/firebase.html#firebase-%E3%81%A8%E3%81%AF%EF%BC%9F

https://firebase.google.com/docs/auth/web/manage-users?hl=ja

https://firebase.google.com/docs/auth/web/github-auth?hl=ja

**Comment by rkdora** [comment]
![image (1)](https://user-images.githubusercontent.com/20394831/81085345-13b53180-8f32-11ea-98dc-31cc6c44ff44.png)
![image](https://user-images.githubusercontent.com/20394831/81085351-157ef500-8f32-11ea-999f-1d033d6d2ee3.png)

**Comment by rkdora** [comment]
https://qiita.com/mironal/items/43dc816596a6fdfb93cc

**Comment by rkdora** [comment]
https://medium.com/firebase-developers/using-firebase-in-electron-tips-and-tricks-24ac5b44bf5a

**Comment by rkdora** [comment]
![image](https://user-images.githubusercontent.com/20394831/81168160-6c87d700-8fd1-11ea-9bd0-4467ef0a0109.png)

**Comment by rkdora** [comment]
https://firebase.google.com/docs/hosting/reserved-urls?authuser=3

**Comment by tanacchi** [comment]
`getRedirectResult` / `signInWithRedirect` なら行けるかも！！

**Comment by tanacchi** [comment]
[ヘルパーを使うパターン](https://github.com/mironal/electron-oauth-helper#firebase-auth-integration) ってコレのことかな？
割といけそうに見えるな

**Comment by rkdora** [comment]
それ。ワクワク(^^)

**Comment by tanacchi** [comment]
`electron` は一旦なしの方向で… :cry:

**Comment by tanacchi** [comment]
自動で閉じてほしいンゴね
