### ISSUE TITLE
リアルタイムコメント機能の仕様

### ISSUE THREAD

**Issue by rkdora** [kyutech-programming-club/lt-hub#27]
- [x] Enter or Button で送信

- [x] トークのサブコレクション

- [x] 構造（content, userRef, createdAt）

- [x] ログインしていないと投稿できない（参加は関係ない）

- [x] 表示は最新が上にくる

- [x] スクロールボックス

ゆくゆくは

- [ ] いいね

**Comment by syu-kwsk** [comment]
できたできた
