### ISSUE TITLE
スマホ修正

### ISSUE THREAD

**Issue by rkdora** [kyutech-programming-club/lt-hub#28]
- [x] LT-Hubのタイトルが潰れる

<img width="343" alt="スクリーンショット 2020-06-13 13 53 34" src="https://user-images.githubusercontent.com/20394831/84560279-5bbf4380-ad7d-11ea-87b1-fbcb7313b542.png">

- [x] ログインできない

**Comment by rkdora** [comment]
https://github.com/firebase/firebaseui-web#configuration

**Comment by rkdora** [comment]
https://firebase.google.com/docs/auth/web/github-auth#before_you_begin

**Comment by syu-kwsk** [comment]
Googleに変えた
