### ISSUE TITLE
コメントにいいね機能

### ISSUE THREAD

**Issue by tetuomi** [kyutech-programming-club/lt-hub#53]
Lt-hubを実際につかってみて、いいね機能欲しいと思いました。
その他意見お願いします

**Comment by rkdora** [comment]
僕も欲しいです

**Comment by rkdora** [comment]
いいねの代わりに、いいねした人のアイコンを小さくして表示させるのもありと思った

**Comment by rkdora** [comment]
それか、単純にハートマークをおいといて
ひとり何回でも押せる＆誰が押したかわからない

**Comment by syu-kwsk** [comment]
Talkにfavoriteフィールドつけてインクリメントだけの数値を保存
