### ISSUE TITLE
ユーザーアンケート(第2回LT会)

### ISSUE THREAD

**Issue by rkdora** [kyutech-programming-club/lt-hub#55]
せっかく皆に触ってもらったので、感想や意見を集めたいなと。
そのためのアンケート項目を考える。
欲しい機能、使いにくかったところなど

**Comment by syu-kwsk** [comment]
- LT-Hubどうでしたか？
- 欲しい機能

    
（使いにくいを分解）
- 見にくかった
- 何すればいいかわからなかった
- 入力しにくかった
- いらないと思った
- その他使いにくかった

**Comment by rkdora** [comment]
今想定している機能を伝えた上で、他に欲しい機能とかその機能はいらないとか

**Comment by syu-kwsk** [comment]
はやめにだしたいよ。6/21かな？（今日じゃん…）
