### ISSUE TITLE
githubの名前が表示されない

### ISSUE THREAD

**Issue by take-cantik** [kyutech-programming-club/lt-hub#7]
![image](https://user-images.githubusercontent.com/50654077/81490928-c4208e00-92c2-11ea-9b34-09625af98a43.png)
名前を設定してない人は名前が表示されない

**Comment by rkdora** [comment]
{"uid":"20394xxx",
"displayName":"Ryuto Kawano",
"photoURL":"https://avatars0.githubusercontent.com/u/20394831?v=4",
"email":"xxxxx@gmail.com",
"phoneNumber":null,
"providerId":"github.com"}

**Comment by rkdora** [comment]
DIsplayNameしかとってこれない

**Comment by tanacchi** [comment]
取ってきた uid とかを利用して Github の API を叩けばいける．
まあ LT-Hub の方で別個に名前設定させても良いんだけどね．

[参考](https://stackoverflow.com/questions/41115618/github-oauth-using-firebase-how-to-get-users-username)
