### ISSUE TITLE
コメント、イベント概要内のURLをリンク化したい

### ISSUE THREAD

**Issue by rkdora** [kyutech-programming-club/lt-hub#71]
クリックしたらジャンプできるように

**Comment by rkdora** [comment]
https://www.bhnt.co.jp/blog/%E9%96%8B%E7%99%BA%E8%A8%80%E8%AA%9E/javascript/javascript-%E6%96%87%E5%AD%97%E5%88%97%E3%81%8B%E3%82%89url%E3%82%92%E6%8A%BD%E5%87%BA%E3%81%97a%E3%82%BF%E3%82%B0%E3%82%92%E5%BC%B5%E3%82%8B%E9%96%A2%E6%95%B0%E3%80%82/

**Comment by rkdora** [comment]
DBに保存する際にaタグで挟み込み、表示するときはv-htmlに流し込むとできそう。
問題は、<script>とか書き込まれたら動きそうなこと（大問題）

**Comment by syu-kwsk** [comment]
@rkdora  さん
マークダウン対応ってことで、表示側でリンクに変換する処理を書くのはどうでしょう。

**Comment by rkdora** [comment]
最高です(￣▽￣)

**Comment by yattinda** [comment]
コピペで済ませたいため正規表現でURLを判別し、リンクにしてみました
markdownブランチを参照してください

問題点
リンクとコメントを同時に入力することができない（リンクのみの入力しかできない）
　　空白分割までは簡単なのですがv-ifで反映させることができませんでした（泣）

**Comment by syu-kwsk** [comment]
## 解決策
1. コメントがリンクかどうかで分割
2. 分割したものをリストに入れる
3. v-forでリストを回す
4. validURLのときは`<a>`, そうじゃないときは`{{}}`で表示
